"""
NIRNAY – Risk Engine Routes

GET /api/risk/{junction_id} – Detailed risk assessment for one junction
GET /api/risk-map           – Heatmap data for all junctions
"""

from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.database import get_db
from app.models.junction import Junction
from app.schemas.risk import (
    JunctionRiskResponse,
    FactorDetail,
    RiskMapResponse,
    RiskMapEntry,
    JunctionRiskTrendResponse,
)
from app.services.risk_engine import calculate_risk, calculate_risk_for_all, determine_trend_direction

router = APIRouter(tags=["Risk Engine"])


# ── GET /api/risk/{junction_id} ──────────────────────────
@router.get(
    "/risk/{junction_id}",
    response_model=JunctionRiskResponse,
    summary="Get risk assessment for a junction",
    description=(
        "Calculates a **real-time risk score** (0–100) for the specified "
        "junction using a weighted multi-factor model.\n\n"
        "The response includes:\n"
        "- Overall score and risk level\n"
        "- Per-factor breakdown (score, weight, contribution, explanation)\n"
        "- Key factors explaining *why* the score is high or low\n\n"
        "**PROTOTYPE** — This is a hackathon demo engine, not an "
        "official risk model."
    ),
    responses={404: {"description": "Junction not found"}},
)
def get_junction_risk(
    junction_id: str,
    db: Session = Depends(get_db),
) -> JunctionRiskResponse:
    """Compute and return the risk assessment for a single junction."""

    junction = (
        db.query(Junction)
        .filter(Junction.junction_id == junction_id)
        .first()
    )
    if junction is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Junction '{junction_id}' not found.",
        )

    result = calculate_risk(db, junction)

    return JunctionRiskResponse(
        junction_id=result.junction_id,
        junction_name=result.junction_name,
        risk_score=result.risk_score,
        risk_level=result.risk_level,
        key_factors=result.key_factors,
        factor_values={
            k: FactorDetail(**v) for k, v in result.factor_values.items()
        },
        calculation_timestamp=result.calculation_timestamp,
        latitude=result.latitude,
        longitude=result.longitude,
        disclaimer=result.disclaimer,
    )


# ── GET /api/risk-map ───────────────────────────────────
@router.get(
    "/risk-map",
    response_model=RiskMapResponse,
    summary="Get risk heatmap for all junctions",
    description=(
        "Returns risk scores for **every junction** in the system, "
        "suitable for rendering a heatmap overlay on the Nagpur map.\n\n"
        "Each entry is a lightweight summary (score, level, key factors, "
        "GPS coordinates). Use `GET /api/risk/{junction_id}` for the "
        "full per-factor breakdown.\n\n"
        "**PROTOTYPE** — simulated data, not a validated risk model."
    ),
)
def get_risk_map(
    db: Session = Depends(get_db),
) -> RiskMapResponse:
    """Compute risk for all junctions and return heatmap data."""

    results = calculate_risk_for_all(db)
    now = datetime.now(timezone.utc).isoformat()

    entries = [
        RiskMapEntry(
            junction_id=r.junction_id,
            junction_name=r.junction_name,
            latitude=r.latitude,
            longitude=r.longitude,
            risk_score=r.risk_score,
            risk_level=r.risk_level,
            key_factors=r.key_factors,
        )
        for r in results
    ]

    # Sort by risk score descending (highest risk first)
    entries.sort(key=lambda e: e.risk_score, reverse=True)

    return RiskMapResponse(
        total_junctions=len(entries),
        calculation_timestamp=now,
        disclaimer=(
            "PROTOTYPE MODEL — These risk scores are generated by a "
            "hackathon demo engine using simulated data. They are NOT "
            "scientifically validated and must NOT be used for real "
            "operational decisions."
        ),
        junctions=entries,
    )


# ── GET /api/risk/{junction_id}/trend ────────────────────
@router.get(
    "/risk/{junction_id}/trend",
    response_model=JunctionRiskTrendResponse,
    summary="Get risk trend for a junction",
    description=(
        "Returns the chronological risk history and detected trend direction "
        "(INCREASING, DECREASING, STABLE) for a specified junction.\n\n"
        "**PROTOTYPE** — simulated data, not a validated risk model."
    ),
    responses={404: {"description": "Junction not found"}},
)
def get_junction_trend(
    junction_id: str,
    db: Session = Depends(get_db),
) -> JunctionRiskTrendResponse:
    """Query risk history and determine risk trend direction."""
    junction = (
        db.query(Junction)
        .filter(Junction.junction_id == junction_id)
        .first()
    )
    if junction is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Junction '{junction_id}' not found.",
        )

    from app.models.risk_history import RiskHistory
    history_records = (
        db.query(RiskHistory)
        .filter(RiskHistory.junction_id == junction_id)
        .order_by(RiskHistory.timestamp.asc())
        .all()
    )

    scores = [h.risk_score for h in history_records]
    trend = determine_trend_direction(scores)

    return JunctionRiskTrendResponse(
        junction_id=junction.junction_id,
        junction_name=junction.junction_name,
        history=history_records,
        trend_direction=trend,
        disclaimer=(
            "PROTOTYPE MODEL — These risk trends are generated by a "
            "hackathon demo engine using simulated data. They are NOT "
            "scientifically validated and must NOT be used for real "
            "operational decisions."
        ),
    )
